
import { Files } from '../types';

const POWERSHELL_PROLOGUE = `
# Generated by Code Studio com Gemini API
# This script attempts to set up and run the project on your local machine.
# Ensure you have the necessary runtimes (e.g., Python, Node.js, .NET) installed.

function Pause-And-Exit {
    Write-Host ""
    Read-Host "Press Enter to exit..."
    Exit
}

`;

export const generatePowerShellScript = (files: Files): { scriptContent: string; fileName: string; error?: string } => {
    const fileNames = Object.keys(files);

    // Python Project
    const pythonAppFile = fileNames.find(f => f === 'app.py' || f === 'main.py' || f.endsWith('.py'));
    if (pythonAppFile) {
        const hasRequirements = fileNames.includes('requirements.txt');
        const scriptContent = `
${POWERSHELL_PROLOGUE}
Write-Host "Detected Python project."

${hasRequirements ? `
Write-Host "Installing dependencies from requirements.txt..."
pip install -r requirements.txt
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error installing Python dependencies. Please check your Python/pip setup." -ForegroundColor Red
    Pause-And-Exit
}
` : ''}

Write-Host "Running Python script: ${pythonAppFile}..."
python ${pythonAppFile}

Pause-And-Exit
`;
        return { scriptContent: scriptContent.trim(), fileName: 'run_project.ps1' };
    }

    // Node.js Project
    const nodeAppFile = fileNames.find(f => f === 'index.js' || f === 'app.js' || f === 'server.js');
    if (nodeAppFile && fileNames.includes('package.json')) {
        const scriptContent = `
${POWERSHELL_PROLOGUE}
Write-Host "Detected Node.js project."

Write-Host "Installing dependencies from package.json..."
npm install
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error installing Node.js dependencies. Please check your Node.js/npm setup." -ForegroundColor Red
    Pause-And-Exit
}

Write-Host "Running Node.js script: ${nodeAppFile}..."
node ${nodeAppFile}

Pause-And-Exit
`;
        return { scriptContent: scriptContent.trim(), fileName: 'run_project.ps1' };
    }

    // C# Project
    const csharpProjectFile = fileNames.find(f => f.endsWith('.csproj'));
    if (csharpProjectFile) {
        const scriptContent = `
${POWERSHELL_PROLOGUE}
Write-Host "Detected C# .NET project."

Write-Host "Restoring dependencies..."
dotnet restore
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error restoring .NET dependencies." -ForegroundColor Red
    Pause-And-Exit
}

Write-Host "Running .NET project..."
dotnet run
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error running the .NET project." -ForegroundColor Red
    Pause-And-Exit
}

Pause-And-Exit
`;
        return { scriptContent: scriptContent.trim(), fileName: 'run_project.ps1' };
    }
    
    // TypeScript project with tsconfig and a ts file, but no package.json (like the example)
    const tsAppFile = fileNames.find(f => f === 'index.ts');
    if(tsAppFile && fileNames.includes('tsconfig.json')) {
         const scriptContent = `
${POWERSHELL_PROLOGUE}
Write-Host "Detected TypeScript project."
Write-Host "This project seems to be a simple TypeScript script without a package.json."
Write-Host "You may need to install 'ts-node' globally to run it: npm install -g ts-node"

Write-Host "Attempting to run with ts-node: ${tsAppFile}..."
ts-node ${tsAppFile}
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error running TypeScript file. Please ensure 'ts-node' is installed and configured." -ForegroundColor Red
    Pause-And-Exit
}

Pause-And-Exit
`;
       return { scriptContent: scriptContent.trim(), fileName: 'run_project.ps1' };
    }


    return { 
        scriptContent: '', 
        fileName: '', 
        error: "Não foi possível determinar como executar este projeto. Nenhum arquivo principal (ex: app.py, index.js) ou arquivo de projeto (.csproj) foi encontrado." 
    };
};
